#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

source = ~/.config/hypr/myprog.conf

exec-once = $terminal
exec-once = nm-applet --indicator &
exec-once = waybar & hyprpaper & firefox
exec-once = steam
exec-once = discord
exec-once = vicinae server
exec-once = systemctl --user start hyprpolkitagent
