# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule = match:class steam, workspace 2, no_initial_focus on
windowrule = match:class discord, workspace 3, no_initial_focus on
